### ISSUE TITLE
Should n't the context be escaped here?

### ISSUE THREAD

**Issue by benzen** [caolan/magery-tests#13]
It seams that in this case the python implementation will escape the attribute data-context:

https://github.com/caolan/magery-tests/blob/7de5f0e4c41a3b09c54be8a2292965d04781ddf2/components/0802-data-embed-on-component-template/expected.html#L2

Maybe I'm wrong

**Comment by caolan** [comment]
Yes, this is again working for me because I'm comparing parsed HTML trees, and they are functionally equivalent.

We could change this to make the tests more predictable when comparing raw output, but perhaps we should also consider standardising on single quotes for data-context, as escaping every double quote in a JSON string could add a lot of bloat to the output?

**Comment by caolan** [comment]
This issue has also been discussed here: https://github.com/caolan/magery-tests/pull/15

**Comment by caolan** [comment]
This is working as per our discussion, so I've opened a ticket for the python library (https://github.com/caolan/python-magery/issues/2) and will close this one.
