### ISSUE TITLE
0402-data-each-access-outer-context expectation may be wrong

### ISSUE THREAD

**Issue by benzen** [caolan/magery-tests#7]
ATM expectations are the following:
```
<app-main>
    <div>item: one</div>
    <div>item: two</div>
    <div>item: three</div>
</app-main>
```

Since the template is as follow
```
<template data-tagname="app-main">
    <div data-each="item in items">{{ prefix }}: {{ item.name }}</div>
</template>
```

I think it should read as follow:
```
<app-main>
    <div>item: one</div><div>item: two</div><div>item: three</div>
</app-main>
```

If I'm wrong please explain where the line return comes from between the div elements

**Comment by caolan** [comment]
Yes, I think you are correct, those newlines should probably be removed.

I suspect there will be other places in the test suite where insignificant whitespace like this is ignored, since my own test runners do their best to compare resulting trees instead of string output. Having predictable string output is desirable for the magery-test suite though.

**Comment by caolan** [comment]
And, to confirm, the Python library produces markup matching your second example (without newlines between each div).

**Comment by caolan** [comment]
Fixed by https://github.com/caolan/magery-tests/pull/10
